index:
  metas:
    title: "Study: Introduction"

edit:
  metas:
    title: "Index"

failedlist:
  metas:
    title: "Study: Failed Kanji List"

mystories:
  metas:
    title: "Study: My Stories List"

# NOTE!  entry-study is currently a common bundle added by coreWebResponse::addViteEntries()
# all:
#   javascripts: [ 'src/entry-study.ts' ]

