# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title: "Kanji Koohii"
    description: 'Study the Japanese characters with James Heisig''s "Remembering the Kanji" method, and review with kanji flashcards.'
    #keywords:     symfony, project
    #language:     en
    #robots:       NE PAS INCLURE ROBOTS SINON CA REMPLACE LE STAGING (cf. layout)

  # DO NOT add global css/js here ==> see coreWebResponse::addViteEntries()
  # javascripts:
  #   - ...

  has_layout: true
  layout: layout
