index:
  metas:
    title: 'Index'
  
shuffle1Success:
  metas:
    title: 'Vocab Shuffle'

  javascripts: [ '/src/labs-alpha-flashcardreview.ts' ]

shuffle2Success:
  metas:
    title: 'Vocab Shuffle'

  javascripts: [ '/src/labs-alpha-flashcardreview.ts' ]

all:
  metas:
    title: 'Labs'
